// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZn7puTUpHsboQJdmbfByL-yfcnkO2elw',
    appId: '1:219134283738:web:29f0fea1d7f67e90f17ae3',
    messagingSenderId: '219134283738',
    projectId: 'asessment-work-scheduler',
    authDomain: 'asessment-work-scheduler.firebaseapp.com',
    storageBucket: 'asessment-work-scheduler.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4C0_oX0tOf9a2nNyNh29DIz_-NkCGysg',
    appId: '1:219134283738:android:af0ba8878b340bcaf17ae3',
    messagingSenderId: '219134283738',
    projectId: 'asessment-work-scheduler',
    storageBucket: 'asessment-work-scheduler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLNNpUW7Wl3U9lz6jVX9pw4j0btoNlcmk',
    appId: '1:219134283738:ios:50cc40c621e00159f17ae3',
    messagingSenderId: '219134283738',
    projectId: 'asessment-work-scheduler',
    storageBucket: 'asessment-work-scheduler.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLNNpUW7Wl3U9lz6jVX9pw4j0btoNlcmk',
    appId: '1:219134283738:ios:50cc40c621e00159f17ae3',
    messagingSenderId: '219134283738',
    projectId: 'asessment-work-scheduler',
    storageBucket: 'asessment-work-scheduler.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZn7puTUpHsboQJdmbfByL-yfcnkO2elw',
    appId: '1:219134283738:web:e39faf1279b32ecbf17ae3',
    messagingSenderId: '219134283738',
    projectId: 'asessment-work-scheduler',
    authDomain: 'asessment-work-scheduler.firebaseapp.com',
    storageBucket: 'asessment-work-scheduler.firebasestorage.app',
  );

}